// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d50a1355-3341-4fad-84ea-4f5511f54dc0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZBBs2eCZu",
    "aws_user_pools_web_client_id": "t214altgktr2pg9fnioqguavl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://eyw2lim4qjd5rmduf5ccigudva.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
